services:
  booktex.service:
    profiles: ["app"]
    image: ${DOCKER_REGISTRY-}booktexservice
    build:
      context: .
      dockerfile: Booktex.Service/Dockerfile
    depends_on:
      - booktex.db

  booktex.db:
    profiles: ["app"]
    container_name: booktex.db.postgres
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb

    environment:
      POSTGRES_PASSWORD: BeUUuzingDis4-P45w0RD
      POSTGRES_DB: booktexdb
      POSTGRES_USER: booktexuser
    ports:
      - 7432:5432

  development.postgres.adminer:
    profiles: ["app"]
    image: adminer
    restart: always
    ports:
      - 7431:8080
